### PR TITLE
Single return after vPortFree()s comms_service

### PR DESCRIPTION
**Pull request by ArashYzd**
Fixing Issue #42

### CODE REVIEW

**Review by Taylorr82 — APPROVED** [review]
Very simple solution. I like it

**Comment by Taylorr82** [comment]
Sidenote: Why do you malloc so much at the start? Would it not be better to only malloc what you need when you need it?

**Comment by ArashYzd** [comment]
@Taylorr82 I think there is an issue of declaring a variable inside a case statement. I think you can add {} scopes to fix that, though. Although, it was before switching to malloc and probably doesn't apply anymore.
Also, for a lot of cases, the same struct will be used, so this saves some lines of codes, though, I agree that it allocates unnecessary memories since only one of those allocated memories is used each time.
So, would you say optimum memory management here is beneficial? I could change this and run a test script to see if it works properly.

**Comment by ArashYzd** [comment]
I'll merge this to get rid of the problem but will keep the issue open as a reminder to improve the code and test it when there is more time.

**Pull request merged**
